version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db  # Use the service name as the hostname
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=disha123
      - POSTGRES_DB=CargoLynxFinal
    depends_on:
      - db
    links:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: disha123
      POSTGRES_DB: CargoLynxFinal
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
